### ISSUE TITLE
Bug in servlet-side space images evenly

### ISSUE THREAD

**Issue by chengwill97** [chengwill97/SANDI-Interactive-Demo#57]
@Sreyasi I am getting a bug while using example articles 3.
I upload all 5 images and the text file, and then I choose the space images evenly checkbox, 
as well as only choosing up to 3 images, but I get a results page with no images and an alignments.txt that is empty. There is no outputted from the server side.

**Comment by Sreyasi** [comment]
is this still a bug?

**Comment by chengwill97** [comment]
> is this still a bug?

Yes, this is still a bug.

**Comment by chengwill97** [comment]
> is this still a bug?

Yes, this is still a bug.

**Comment by Sreyasi** [comment]
I think once you make the changes in #55 this should be resolved

**Comment by chengwill97** [comment]
@Sreyasi I made the changes in #55 but I still don't get what we expect.

I tried example 1, and I put in the number of images to include as 2, but I only get 1 image as a result.

**Comment by Sreyasi** [comment]
Did you commit the changes? where can I see the changes to #55?

**Comment by chengwill97** [comment]
> Did you commit the changes? where can I see the changes to #55?

It's in the bug-55 branch. I made the change in ILPBased.java

**Comment by Sreyasi** [comment]
> @Sreyasi I made the changes in #55 but I still don't get what we expect.
> 
> I tried example 1, and I put in the number of images to include as 2, but I only get 1 image as a result.

I remember once we encountered this error before. If the image is being aligned to the last paragraph it wasn't displayed...are you sure it's not the same error?

**Comment by Sreyasi** [comment]
Oh I think there's a bug.
Change numImages in lines 208 and 209 to imageName_tags.size()

**Comment by chengwill97** [comment]
@Sreyasi This doesn't seem to resolve the issue. I kept the java server up with the changes you've suggested.

**Comment by Sreyasi** [comment]
can you please try to debug it? eclipse (if you're still using it for the java parts) has a nice debug environment. i can't see the reason for the error.

If you don't have enough time, just leave out the equal spacing option for now.

**Comment by Sreyasi** [comment]
We need to re-visit this.

**Comment by Sreyasi** [comment]
Any updates?

**Comment by Sreyasi** [comment]
Looks like we tried the feature which evenly spaces out images. The bug appears when user provides input for the number of images to be selected. Need to debug this.
